CREATE TABLE IF NOT EXISTS `salesperson` (
	`staff_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
	`country_id` BIGINT UNSIGNED NOT NULL,
	PRIMARY KEY(`staff_id`)
);


CREATE TABLE IF NOT EXISTS `country` (
	`country_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`country_name` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`country_id`)
);


CREATE TABLE IF NOT EXISTS `region` (
	`region_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`state_province` VARCHAR(255) NOT NULL,
	`country_id` BIGINT UNSIGNED NOT NULL,
	PRIMARY KEY(`region_id`)
);


CREATE TABLE IF NOT EXISTS `city` (
	`city_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`city_name` VARCHAR(255) NOT NULL,
	`region_id` BIGINT UNSIGNED NOT NULL,
	PRIMARY KEY(`city_id`)
);


CREATE TABLE IF NOT EXISTS `address` (
	`add_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`address` VARCHAR(255) NOT NULL,
	`zip_postal_code` INTEGER NOT NULL,
	`city_id` BIGINT UNSIGNED NOT NULL,
	PRIMARY KEY(`add_id`)
);


CREATE TABLE IF NOT EXISTS `customers` (
	`customer_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
	`cust_name` VARCHAR(255) NOT NULL,
	`phone_num` VARCHAR(255) NOT NULL,
	`email` VARCHAR(255) NOT NULL,
	`country_id` BIGINT UNSIGNED NOT NULL,
	PRIMARY KEY(`customer_id`)
);


CREATE TABLE IF NOT EXISTS `invoices` (
	`invoice_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`staff_id` BIGINT UNSIGNED NOT NULL,
	`customer_id` BIGINT UNSIGNED NOT NULL,
	`sale` INTEGER NOT NULL,
	`VIN` VARCHAR(255) NOT NULL,
	`date` DATE NOT NULL,
	PRIMARY KEY(`invoice_id`)
);


CREATE TABLE IF NOT EXISTS `cars` (
	`VIN` VARCHAR(255) NOT NULL,
	`manufacturer` VARCHAR(255) NOT NULL,
	`model` VARCHAR(255) NOT NULL,
	`year` YEAR NOT NULL,
	`color` VARCHAR(255) NOT NULL,
	`invoice_id` BIGINT UNSIGNED NOT NULL,
	PRIMARY KEY(`VIN`)
);


ALTER TABLE `address`
ADD FOREIGN KEY(`city_id`) REFERENCES `city`(`city_id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `city`
ADD FOREIGN KEY(`region_id`) REFERENCES `region`(`region_id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `region`
ADD FOREIGN KEY(`country_id`) REFERENCES `country`(`country_id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `salesperson`
ADD FOREIGN KEY(`country_id`) REFERENCES `country`(`country_id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `invoices`
ADD FOREIGN KEY(`staff_id`) REFERENCES `salesperson`(`staff_id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `invoices`
ADD FOREIGN KEY(`customer_id`) REFERENCES `customers`(`customer_id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `customers`
ADD FOREIGN KEY(`country_id`) REFERENCES `country`(`country_id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `invoices`
ADD FOREIGN KEY(`VIN`) REFERENCES `cars`(`VIN`)
ON UPDATE NO ACTION ON DELETE NO ACTION;